version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: curdapp
      MYSQL_USER: joy
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  tomcat:
    build: .
    container_name: tomcat-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: joy
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "9292:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
